[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers]
  docker = true
  file = { filename = "/etc/traefik/dynamic_conf.toml", watch = true }

[log]
  level = "DEBUG"

[api]
  dashboard = true
